# Generated by Django 3.1.7 on 2021-03-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dueDate',
            new_name='due_date',
        ),
    ]
